SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE tags RESTART IDENTITY;
TRUNCATE TABLE post_tags RESTART IDENTITY;
TRUNCATE TABLE comments RESTART IDENTITY;
TRUNCATE TABLE posts RESTART IDENTITY;
SET REFERENTIAL_INTEGRITY TRUE;